package constants

const (
	EMAIL_ADMIN_RMS = "rms.admin@test.com"

	WORKER_ROLE = "WORKER"
	ADMIN_ROLE  = "ADMIN"

	SHIFT_REQUEST_STATUS_PENDING  = "PENDING"
	SHIFT_REQUEST_STATUS_REJECTED = "REJECTED"
	SHIFT_REQUEST_STATUS_APPROVED = "APPROVED"

	MAX_ASSIGNED_SHIFT_PER_WEEK = 5
)
